### ISSUE TITLE
Try to install through pod.

### ISSUE THREAD

**Issue by kanak14** [Krivoblotsky/ActionPicker#4]
Analyzing dependencies
[!] Unable to find a specification for `ActionPicker`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by Krivoblotsky** [comment]
Thanks. I’ll take a look on this soon.

**Comment by Krivoblotsky** [comment]
Hey, @kanak14
Could you please clarify the steps to reproduce the issue?
I've tried to install the pod from several machines and everything is fine for me:
```
# krivoblotsky @ Sergiis-MacBook-Pro in ~/Desktop/PPD [9:41:14]
$ pod install
Analyzing dependencies
Downloading dependencies
Installing ActionPicker (0.1.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `PPD.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

**Comment by Krivoblotsky** [comment]
I've also tried to install the Pod into `Example` folder:
```
# krivoblotsky @ Sergiis-MacBook-Pro in ~/Work/Home/ActionPicker/Example on git:master x [9:48:37]
$ pod install
Analyzing dependencies
Fetching podspec for `ActionPicker` from `../`
Downloading dependencies
Installing ActionPicker 0.1.0
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

**Comment by kanak14** [comment]
Hello Krivoblotsky,

Not working CocoaPods version 1.0 after update CocoaPods version install successful ActionPicker.

**Comment by Krivoblotsky** [comment]
Got it. Closing the ticket.
